version: "3.5"

networks:
  odp-identity-net:
    name: odp-identity-net

services:
  odp-identity:
    container_name: odp-identity
    build:
      context: .
      args:
        - PROXY_IP
    networks:
      - odp-identity-net
    ports:
      - "9024:9024"
    environment:
      - FLASK_APP=odpidentity
      - FLASK_ENV
      - FLASK_SECRET_KEY
      - DATABASE_URL
      - MAIL_SERVER
      - OAUTH2_CLIENT_ID=odp-identity
      - OAUTH2_CLIENT_SECRET
      - OAUTH2_SCOPES=openid
      - HYDRA_PUBLIC_URL
      - HYDRA_ADMIN_URL
      - HYDRA_LOGIN_EXPIRY
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    restart: always
